name: generate ascii artwork

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List repo files
        run: ls -ltra  # ✅ spacing for clarity

      - name: Executing shell script
        run: 
          chmod +x ascii-shell.sh
          ./ascii-shell.sh

