name: generate ascii artwork

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make shell script executable
        run: chmod +x .github/workflows/ascii-shell.sh

      - name: Run dragon script
        run: .github/workflows/ascii-shell.sh
